---
- name: Gather Cisco IOS Facts
  hosts: all
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Get device facts
      ios_facts:

    - name: Display hardware and software details
      debug:
        msg: >
          The hostname is {{ ansible_net_hostname }} 
          running version {{ ansible_net_version }}.
